# Generated by Django 6.1.1 on 2026-10-04 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('item', models.CharField(choices=[('ALUMBRADO_PUBLICO', 'Alumbrado público'), ('ATENCION_SOCIAL', 'Atención social'), ('INFRAESTRUCTURA', 'Infraestructura y mantención'), ('ASEO_ORNATO', 'Aseo y ornato'), ('OTRO', 'Otro')], max_length=30)),
                ('solicitud_problema', models.TextField()),
                ('accion_realizada', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('servicio', models.CharField(blank=True, max_length=100)),
                ('agenda_colectiva', models.BooleanField(default=False)),
                ('estado', models.CharField(default='registrada', max_length=30)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('solicitante', models.CharField(max_length=150)),
                ('territorio', models.CharField(blank=True, max_length=150)),
                ('area_apoyo', models.CharField(blank=True, max_length=150)),
                ('origen', models.CharField(default='interna', max_length=20)),
                ('fecha_compromiso', models.DateField()),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('REALIZADO', 'Realizado')], default='INGRESADO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_revision', models.CharField(default='sin_archivo', max_length=30)),
                ('metadatos', models.TextField(blank=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='operacion.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('VERIFICADOR', 'Verificador')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('SOLICITA_CORRECCION', 'Solicita corrección')], max_length=25)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='operacion.evidencia')),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
