# Generated by Django 6.1.1 on 2026-10-04 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='accion_realizada',
            field=models.CharField(max_length=255, verbose_name='Acción ejecutada'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='agenda_colectiva',
            field=models.BooleanField(default=False, verbose_name='Relacionar con agenda colectiva'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(default='registrada', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='item',
            field=models.CharField(choices=[('ALUMBRADO_PUBLICO', 'Alumbrado público'), ('ATENCION_SOCIAL', 'Atención social'), ('INFRAESTRUCTURA', 'Infraestructura y mantención'), ('ASEO_ORNATO', 'Aseo y ornato'), ('OTRO', 'Otro')], max_length=30, verbose_name='Ítem'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='solicitud_problema',
            field=models.TextField(verbose_name='Actividad / Solicitud / Problema'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='area_apoyo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Área de apoyo'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='estado',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('REALIZADO', 'Realizado')], default='INGRESADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='fecha_compromiso',
            field=models.DateField(verbose_name='Fecha comprometida'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='origen',
            field=models.CharField(default='interna', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='solicitante',
            field=models.CharField(max_length=150, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='territorio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Territorio'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='codigo',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='estado_revision',
            field=models.CharField(default='sin_archivo', max_length=30, verbose_name='Estado de revisión'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='metadatos',
            field=models.TextField(blank=True, verbose_name='Metadatos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('VERIFICADOR', 'Verificador')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='decision',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('SOLICITA_CORRECCION', 'Solicita corrección')], max_length=25, verbose_name='Decisión'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='fecha_validacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de validación'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
    ]
