# Generated by Django 6.1.1 on 2026-10-05 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_alter_actividad_accion_realizada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100, verbose_name='Evento')),
                ('origen', models.CharField(max_length=50, verbose_name='Origen')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('entidad_afectada', models.CharField(max_length=50, verbose_name='Entidad afectada')),
                ('id_registro', models.CharField(max_length=20, verbose_name='ID del registro')),
                ('valor_anterior', models.CharField(blank=True, max_length=255, verbose_name='Valor anterior')),
                ('valor_nuevo', models.CharField(blank=True, max_length=255, verbose_name='Valor nuevo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
    ]
