# Generated by Django 6.1.1 on 2026-10-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_auditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.AlterModelOptions(
            name='compromiso',
            options={'verbose_name': 'Compromiso', 'verbose_name_plural': 'Compromisos'},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='validacion',
            options={'verbose_name': 'Validación', 'verbose_name_plural': 'Validaciones'},
        ),
    ]
