# Generated by Django 6.1.1 on 2026-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_alter_actividad_options_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('VERIFICADOR', 'Verificador'), ('ADMINISTRADOR', 'Administrador')], max_length=20, verbose_name='Rol'),
        ),
    ]
